development:
  adapter: postgresql
  encoding: unicode
  database: home-automation
  pool: 5
  username: doutatsu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: home-automation
  pool: 5
  username: doutatsu
  password: